import type { Metadata } from 'next'
import { Space_Grotesk } from 'next/font/google'
import './globals.css'

const inter = Space_Grotesk({ weight: ["400", "500", "600", "700"], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'OurApp',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='h-full w-full'>
      <body className={`${inter.className} h-full w-full`}>
        <div className='h-full w-full bg-black text-white'>
          {children}
        </div>
      </body>
    </html>
  )
}
